export const GET_DECKS_REQUEST = "GET_DECKS_REQUEST";
export const GET_DECKS_SUCCESS = "GET_DECKS_SUCCESS";
export const GET_DECKS_ERROR = "GET_DECKS_ERROR";
export const GET_DECK = "GET_DECK";
export const GET_DECK_REQUEST = "GET_DECK_REQUEST";
export const GET_DECK_ERROR = "GET_DECK_ERROR";

export const DECK_CREATE_REQUEST = "DECK_CREATE_REQUEST";
export const DECK_CREATE_SUCCESS = "DECK_CREATE_SUCCESS";
export const DECK_CREATE_ERROR = "DECK_CREATE_ERROR";
export const DECK_CREATE_RESET = "DECK_CREATE_RESET";

export const DECK_DELETE_REQUEST = "DECK_DELETE_REQUEST";
export const DECK_DELETE_SUCCESS = "DECK_DELETE_SUCCESS";
export const DECK_DELETE_FAIL = "DECK_DELETE_FAIL";

export const UPDATE_DECK_REQUEST = "UPDATE_DECK_REQUEST";
export const UPDATE_DECK_SUCCESS = "UPDATE_DECK_SUCCESS";
export const UPDATE_DECK_FAIL = "UPDATE_DECK_FAIL";

export const UPDATE_DECK_CARDS_FAIL = "UPDATE_DECK_CARDS_FAIL";
export const UPDATE_DECK_CARDS_SUCCESS = "UPDATE_DECK_CARDS_SUCCESS";
export const UPDATE_DECK_CARDS_REQUEST = "UPDATE_DECK_CARDS_REQUEST";
export const UPDATE_DECK_CARDS_ADD_SUCCESS = "UPDATE_DECK_CARDS_ADD_SUCCESS";

export const GET_CARDS_REQUEST = "GET_CARDS_REQUEST";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAIL = "GET_CARDS_FAIL";
export const CARDS_CLEAR = "CARDS_CLEAR";
