export const GET_DECKS_REQUEST = "GET_DECKS_REQUEST";
export const GET_DECKS_SUCCESS = "GET_DECKS_SUCCESS";
export const GET_DECKS_ERROR = "GET_DECKS_ERROR";
export const GET_DECK = "GET_DECK";
export const GET_DECK_REQUEST = "GET_DECK_REQUEST";
export const GET_DECK_ERROR = "GET_DECK_ERROR";

export const DECK_CREATE_REQUEST = "DECK_CREATE_REQUEST";
export const DECK_CREATE_SUCCESS = "DECK_CREATE_SUCCESS";
export const DECK_CREATE_ERROR = "DECK_CREATE_ERROR";
export const DECK_CREATE_RESET = "DECK_CREATE_RESET";

export const DECK_DELETE_REQUEST = "DECK_DELETE_REQUEST";
export const DECK_DELETE_SUCCESS = "DECK_DELETE_SUCCESS";
export const DECK_DELETE_FAIL = "DECK_DELETE_FAIL";
